---
abstract: 'Experimental module'
author:
  - 'Kaare Rasmussen <kaare@cpan.org>'
build_requires:
  File::Find: 0
  File::Temp: 0
  Module::Build: 0.3601
  Test::More: 0
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.102341, CPAN::Meta::Converter version 2.102400'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Jet
no_index:
  directory:
    - t
    - xt
    - examples
    - corpus
provides:
  Jet:
    file: lib/Jet.pm
    version: 0.001
requires:
  perl: 5.006
resources:
  homepage: http://github.com/kaare/Jet/tree
  repository: git://github.com/kaare/Jet.git
version: 0.001
